# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZJDefine' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for ZJDefine

end
